### ISSUE TITLE
关于 X-Bogus 和 _signature 

### ISSUE THREAD

**Issue by New2en** [bincooo/coze-api#3]
请问是否 可以 提供 生成   X-Bogus 和 _signature  算法的代码

**Comment by bincooo** [comment]
此处有说明

https://github.com/CrazyCreativeDream/Real-Coze-API/issues/7

**Comment by New2en** [comment]
已经看到那个讨论，还是十分感谢

**Comment by zhepamagod** [comment]
> 已经看到那个讨论，还是十分感谢

webmssdk中两个函数:
_0x2ae157 
_0x1ae21a

就提示到这里了
