### ISSUE TITLE
You have exceeded the daily limit for sending messages to the bot. Please try again later.

### ISSUE THREAD

**Issue by jonntd** [bincooo/coze-api#4]
这限制的整个账号么

**Comment by bincooo** [comment]
是的，建议创多个账号用oneapi管理即可

**Comment by jonntd** [comment]
怎么切换 gpt4 8k 和 gpt3.5

**Comment by bincooo** [comment]
这个是golang的调用库，你想切换就用你的coze账号创建对应的bot。
如果你使用的是 `bincooo/chatgpt-adapter` 这个项目，那没有提供具体的手动切换方式，只内置了8k token上下文内使用8k，超过8k使用128k的方式
