### ISSUE TITLE
如何生成签名...

### ISSUE THREAD

**Issue by zhepamagod** [bincooo/coze-api#5]
webmssdk中两个函数:
_0x2ae157
_0x1ae21a
浏览器中覆盖源文件后可以调用.

现在我的思路是使用electron登录后,然后重新导入修改后的文件.并暴露这两个函数进行使用..

.不知道你在hf网站的api是怎么实现的..可以交流下吗?

**Comment by zhepamagod** [comment]
![image](https://github.com/bincooo/coze-api/assets/169280828/33e169a7-06f7-44d6-bf77-f0e7d4937fc2)

写了个能和多个大模型同时聊天的软件..
依托electron用是可以了.再想想怎么对外实现api

**Comment by zhepamagod** [comment]
问题已解决..但是还是好奇你是怎么实现的

**Comment by bincooo** [comment]
将js文件拷下来，用node补充环境
